apiVersion: railway.app/v1
name: portfolio-backend
description: FastAPI backend for Albee John's portfolio

environments:
  production:
    name: production
    variables:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CORS_ORIGINS: https://albeejohn.github.io,https://www.albeejohn.github.io
      ENVIRONMENT: production
      PORT: 8000

services:
  backend:
    name: backend
    source:
      path: ./backend
    build:
      command: pip install -r requirements.txt
    start:
      command: uvicorn server:app --host 0.0.0.0 --port $PORT
    health_check:
      path: /api/health
      port: $PORT