# Railway deployment configuration
[build]
builder = "NIXPACKS"

[build.env]
PYTHON_VERSION = "3.11"

[deploy]
startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10