name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Check for yarn.lock and install dependencies
      run: |
        cd frontend
        if [ -f "yarn.lock" ]; then
          echo "Using Yarn"
          npm install -g yarn
          yarn install --frozen-lockfile
        else
          echo "Using npm"
          npm ci
        fi
        
    - name: Build project
      run: |
        cd frontend
        if [ -f "yarn.lock" ]; then
          REACT_APP_BACKEND_URL=https://albeejohn-portfolio-backend.up.railway.app yarn build
        else
          REACT_APP_BACKEND_URL=https://albeejohn-portfolio-backend.up.railway.app npm run build
        fi
      env:
        CI: false
        
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend/build
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4